// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqLC1L8fXU0qriE-BCRveBVPyEb9-oySA',
    appId: '1:648054978069:web:ba5d20175be951cacec01c',
    messagingSenderId: '648054978069',
    projectId: 'psicologo-app',
    authDomain: 'psicologo-app.firebaseapp.com',
    storageBucket: 'psicologo-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABsUK-N9oTooq6dlyG-OOP--AzGY_9Xbs',
    appId: '1:648054978069:android:72e286efd44ba136cec01c',
    messagingSenderId: '648054978069',
    projectId: 'psicologo-app',
    storageBucket: 'psicologo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnOM1Cgyvs8lV1i1MZIxhV272IXw6sAD0',
    appId: '1:648054978069:ios:224bd8779312f9eecec01c',
    messagingSenderId: '648054978069',
    projectId: 'psicologo-app',
    storageBucket: 'psicologo-app.appspot.com',
    iosClientId:
        '648054978069-36hrff3lef3urggl15ffdq1mc0vko4i4.apps.googleusercontent.com',
    iosBundleId: 'com.gracielabessa.psicologo.app',
  );
}
